type StaffDto = {
  Phone: string;
  MarriageStatus: string;
  Password: string;
  AccountStatus: string;
  FullName: string;
  DateOfBirth: string;
  HealthStatus: string;
  Checkin: string[];
  Role: string[];
  Gender: string;
  Avatar: Attachments[];
  Tokens: string[];
  StartWorkingDay: string;
  Username: string;
  PersonalEmail: string;
  ContractType: string;
  Collaboratory: string;
  WorkingPlace: string;
  WorkingPeriod: string;
  "Tasks (Supervisor)": string[];
  Portrait: Attachments[];
  CurriculumVitae: Attachments[];
  WorkingStatus: string;
  WorkingType: string;
  "Tasks (AssignedTo)": string[];
  Notes: string;
  RoleType: string[];
  Company: string[];
  CurrentWorkingPlace: string[];
  DatabaseAccessibility: string[];
  CreatedTime: string;
  LastModifiedTime: string;
  BirthdayCelebration: string;
  StaffId: string;
  Domain: string[];
  Account: string;
};
