import PrimarySearchAppBar from "@/components/layout/PrimarySearchAppBar";
import "./globals.css";
import { Inter } from "next/font/google";
import GlobalLoading from "@/components/layout/GlobalLoading";

const inter = Inter({ subsets: ["latin", "vietnamese"] });

export const metadata = {
  title: "Empla - Human Resources Management Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrimarySearchAppBar />
        <GlobalLoading />
        {children}
      </body>
    </html>
  );
}
